### ISSUE TITLE
Is wbit reversed?

### ISSUE THREAD

**Issue by msmarks** [megahoneybadger/hsms#23]
https://github.com/megahoneybadger/hsms/blob/31b1dab6e2801dada6786946faa7b4c5ffeac6a6/src/coding/encoder.js#L340-L351

In SEMI E37, 8.2.1

> The most significant bit (bit 7) of Header Byte 2 is the W-Bit. In a Primary Message, the W-Bit indicates
whether the Primary Message expects a Reply message. A Primary Message which expects a Reply should set
the W-Bit to 1. A Primary Message which does not expect a Reply should set the W-Bit to 0. 

So should line 347 be like this?
`let wbit =  ( ( m.replyExpected ) ? 128 : 0 );`

**Comment by megahoneybadger** [comment]
You are right.

I ported this project from my old well tested C# version:
`var wbit = ( byte )( ( Reply.None == ReplyType ) ? 0 : 128 );`

Decided to get rid of enums and made this mistake.
